### ISSUE TITLE
2023年后的课程号获取不到

### ISSUE THREAD

**Issue by moye12325** [WuliAPO/Fuck_QCZJ#13]
好像进入2023年获取不到课程号，一直是'course': 'C0123'
之前一直稳定运行，今天一看在1月2号的时候能获取到AccessToken 获取到最新课程代号: C0123签到结果: {"status":400,"message":"选定的课程已结束学习","result":null,"debug":null}
签到失败！

**Comment by WuliAPO** [comment]
再试一下？2023年的课程这周才开始，我刚试了下是 C0124 了

**Comment by moye12325** [comment]
> 再试一下？2023年的课程这周才开始，我刚试了下是 C0124 了

嗯嗯 试了一下，可以获取到了。应该是今天通知学习，我看了下日志，日志记录的是昨天的内容，所以没获取到。
